/*
 *    Class definition of irq_in port for component <SD_AXIv2_DummyGraphicsMacroModel>
 *
 *    This code has been generated by the SoC Designer Component Wizard.
 *    Copyright (c)  2008-2010 Carbon Design Systems Inc.
 *
 * THIS SOFTWARE CONTAINS CONFIDENTIAL INFORMATION AND TRADE SECRETS OF CARBON
 * DESIGN SYSTEMS, INC.  PERMISSION IS HEREBY GRANTED TO USE, MODIFY, AND/OR COPY
 * THIS SOFTWARE FOR INTERNAL USE ONLY PROVIDED THAT THE ABOVE COPYRIGHT NOTICE
 * APPEARS IN ALL COPIES OF THIS SOFTWARE.
 */

#ifndef DummyGraphicsMacroModel_interrupt_SS_h
#define DummyGraphicsMacroModel_interrupt_SS_h

#include "maxsimCompatibility.h"
#include "fj_datatype.h" /* add by katomasa 20110620 */

class SD_AXIv2_DummyGraphicsMacroModel;

template<class WrapperClass>
class DummyGraphicsMacroModel_interrupt_SS: public CASISignalSlave
{
  WrapperClass *owner;
  int portID;
  
 public:
  DummyGraphicsMacroModel_interrupt_SS( WrapperClass *_owner, int _portID );
  virtual ~DummyGraphicsMacroModel_interrupt_SS() {}
  
 public:
  /* Access functions */
  virtual void     driveSignal(uint32_t value, uint32_t* extValue);
  virtual uint32_t readSignal();
  virtual void     readSignal(uint32_t* value, uint32_t* extValue);
};

#endif

