/*
 *    Class definition of reset_x port for component <SD_AXIv2_DummyGraphicsMacroModel>
 *
 *    This code has been generated by the SoC Designer Component Wizard.
 *    Copyright (c)  2008-2010 Carbon Design Systems Inc.
 *
 * THIS SOFTWARE CONTAINS CONFIDENTIAL INFORMATION AND TRADE SECRETS OF CARBON
 * DESIGN SYSTEMS, INC.  PERMISSION IS HEREBY GRANTED TO USE, MODIFY, AND/OR COPY
 * THIS SOFTWARE FOR INTERNAL USE ONLY PROVIDED THAT THE ABOVE COPYRIGHT NOTICE
 * APPEARS IN ALL COPIES OF THIS SOFTWARE.
 */

#ifndef _DummyGraphicsMacroModel_reset_x_SS_H_
#define _DummyGraphicsMacroModel_reset_x_SS_H_

#include "maxsimCompatibility.h"
#include "fj_datatype.h" /* add by katomasa 20110620 */

class SD_AXIv2_DummyGraphicsMacroModel;

template<class WrapperClass>
class DummyGraphicsMacroModel_reset_x_SS: public CASISignalSlave
{
  WrapperClass *owner;

public:
  DummyGraphicsMacroModel_reset_x_SS( WrapperClass *_owner );
  virtual ~DummyGraphicsMacroModel_reset_x_SS() {}

public:
  /* Access functions */
  virtual void     driveSignal(uint32_t value, uint32_t* extValue);
  virtual uint32_t readSignal();
  virtual void     readSignal(uint32_t* value, uint32_t* extValue);
};

#endif

