/*
 *    Class implementation of data_in port for component <SD_AXIv2_DummyGraphicsMacroModel>
 *
 *    This code has been generated by the SoC Designer Component Wizard.
 *    Copyright (c)  2008-2010 Carbon Design Systems Inc.
 *
 * THIS SOFTWARE CONTAINS CONFIDENTIAL INFORMATION AND TRADE SECRETS OF CARBON
 * DESIGN SYSTEMS, INC.  PERMISSION IS HEREBY GRANTED TO USE, MODIFY, AND/OR COPY
 * THIS SOFTWARE FOR INTERNAL USE ONLY PROVIDED THAT THE ABOVE COPYRIGHT NOTICE
 * APPEARS IN ALL COPIES OF THIS SOFTWARE.
 */

#include "DummyGraphicsMacroModel_data_in_SS.h"
#ifdef USE_JPEG
#include "JPEG.h"
#endif
#ifdef USE_IIP
#include "IIP.h"
#endif
#ifdef USE_IIP_Pseudo
#include "IIP_Pseudo.h"
#endif

template<class WrapperClass>
DummyGraphicsMacroModel_data_in_SS<WrapperClass>::DummyGraphicsMacroModel_data_in_SS( WrapperClass *_owner, int _portID ) : CASISignalSlave( "DummyGraphicsMacroModel_data_in_SS" )

{
  owner = _owner;
  setCASIOwner(owner);
  CASISignalProperties prop;
  memset(&prop,0,sizeof(prop));
  prop.isOptional=false;
  prop.bitwidth=32;
  setProperties(&prop);
  
  portID = _portID;

  // TODO:  Add any additional constructor code here.
}

/* Access functions */
template<class WrapperClass>
void
DummyGraphicsMacroModel_data_in_SS<WrapperClass>::driveSignal(uint32_t value, uint32_t* extValue)
{
/* add by katomasa start 20110712 */
  //std::cout << "[INFO] DummyGraphicsMacroModel_data_in_SS<WrapperClass>::driveSignal data_in = " << value 
  //          << ", portID = " << portID << " at " << sc_time_stamp() << std::endl;
/* add by katomasa end 20110712 */

/* commentout by katomasa 20110712 
  switch ( portID ) 
  {
  case 0:
    // TODO:  Add your code here.
    break;
  case 1:
    // TODO:  Add your code here.
    break;
  case 2:
    // TODO:  Add your code here.
    break;
  case 3:
    // TODO:  Add your code here.
    break;
  }
*/
/* add by katomasa start 20110620 */
  owner->core->m_data_in[portID] = (uint32_t)value;
/* add by katomasa end 20110620 */
}

template<class WrapperClass>
uint32_t
DummyGraphicsMacroModel_data_in_SS<WrapperClass>::readSignal()
{
  switch ( portID ) 
  {
  case 0:
    // TODO:  Add your code here.
    break;
  case 1:
    // TODO:  Add your code here.
    break;
  case 2:
    // TODO:  Add your code here.
    break;
  case 3:
    // TODO:  Add your code here.
    break;
  }
  return 0;
}

template<class WrapperClass>
void
DummyGraphicsMacroModel_data_in_SS<WrapperClass>::readSignal(uint32_t* value, uint32_t* extValue)
{
  switch ( portID ) 
  {
  case 0:
    // TODO:  Add your code here.
    break;
  case 1:
    // TODO:  Add your code here.
    break;
  case 2:
    // TODO:  Add your code here.
    break;
  case 3:
    // TODO:  Add your code here.
    break;
  }
}

#ifdef USE_JPEG
template class DummyGraphicsMacroModel_data_in_SS<JPEG>;
#endif
#ifdef USE_IIP
template class DummyGraphicsMacroModel_data_in_SS<IIP>;
#endif
#ifdef USE_IIP_Pseudo
template class DummyGraphicsMacroModel_data_in_SS<IIP_Pseudo>;
#endif
