/*
 *    Class implementation of reset_x port for component <SD_AXIv2_DummyGraphicsMacroModel>
 *
 *    This code has been generated by the SoC Designer Component Wizard.
 *    Copyright (c)  2008-2010 Carbon Design Systems Inc.
 *
 * THIS SOFTWARE CONTAINS CONFIDENTIAL INFORMATION AND TRADE SECRETS OF CARBON
 * DESIGN SYSTEMS, INC.  PERMISSION IS HEREBY GRANTED TO USE, MODIFY, AND/OR COPY
 * THIS SOFTWARE FOR INTERNAL USE ONLY PROVIDED THAT THE ABOVE COPYRIGHT NOTICE
 * APPEARS IN ALL COPIES OF THIS SOFTWARE.
 */

#include "DummyGraphicsMacroModel_reset_x_SS.h"
#ifdef USE_SD_AXIv2_DummyGraphicsMacroModel
#include "SD_AXIv2_DummyGraphicsMacroModel.h"
#endif
#ifdef USE_SD_AXIv2_DummyGraphicsMacroModel2Axi
#include "SD_AXIv2_DummyGraphicsMacroModel2Axi.h"
#endif
#ifdef USE_BufferlessModel
#include "BufferlessModel.h"
#endif
#ifdef USE_JPEG
#include "JPEG.h"
#endif
#ifdef USE_IIP_Pseudo
#include "IIP_Pseudo.h"
#endif

template<class WrapperClass>
DummyGraphicsMacroModel_reset_x_SS<WrapperClass>::DummyGraphicsMacroModel_reset_x_SS( WrapperClass *_owner ) : CASISignalSlave( "DummyGraphicsMacroModel_reset_x_SS" )

{
  owner = _owner;
  setCASIOwner(owner);
  CASISignalProperties prop;
  memset(&prop,0,sizeof(prop));
  prop.isOptional=false;
  prop.bitwidth=32;
  setProperties(&prop);
	
  // TODO:  Add any additional constructor code here.
}

/* Access functions */
template<class WrapperClass>
void
DummyGraphicsMacroModel_reset_x_SS<WrapperClass>::driveSignal(uint32_t value, uint32_t* extValue)
{
  // TODO: Add your code here.

/* add by katomasa start 20110620 */
  owner->m_signal_reset_x.write((bool)value);
/* add by katomasa end 20110620 */
}

template<class WrapperClass>
uint32_t
DummyGraphicsMacroModel_reset_x_SS<WrapperClass>::readSignal()
{
  // TODO: Add your code here.

  //return 0;
/* add by katomasa start 20110620 */
  return (fj::uint32)owner->m_signal_reset_x.read();
/* add by katomasa end 20110620 */
}

template<class WrapperClass>
void
DummyGraphicsMacroModel_reset_x_SS<WrapperClass>::readSignal(uint32_t* value, uint32_t* extValue)
{
  // TODO: Add your code here.

/* add by katomasa start 20110620 */
  fj::uint32 tmp_value = (fj::uint32)owner->m_signal_reset_x.read();
  value = &tmp_value;
/* add by katomasa end 20110620 */
}

#ifdef USE_SD_AXIv2_DummyGraphicsMacroModel
template class DummyGraphicsMacroModel_reset_x_SS<SD_AXIv2_DummyGraphicsMacroModel>;
#endif
#ifdef USE_SD_AXIv2_DummyGraphicsMacroModel2Axi
template class DummyGraphicsMacroModel_reset_x_SS<SD_AXIv2_DummyGraphicsMacroModel2Axi>;
#endif
#ifdef USE_BufferlessModel
template class DummyGraphicsMacroModel_reset_x_SS<BufferlessModel>;
#endif
#ifdef USE_JPEG
template class DummyGraphicsMacroModel_reset_x_SS<JPEG>;
#endif
#ifdef USE_IIP_Pseudo
template class DummyGraphicsMacroModel_reset_x_SS<IIP_Pseudo>;
#endif

