/*
 *    Class definition of AXIv2_master port for component <SD_AXIv2_DummyGraphicsMacroModel>
 *
 *    This code has been generated by the SoC Designer Component Wizard.
 *    Copyright (c)  2008 Carbon Design Systems Inc.
 *
 * THIS SOFTWARE CONTAINS CONFIDENTIAL INFORMATION AND TRADE SECRETS OF CARBON
 * DESIGN SYSTEMS, INC.  PERMISSION IS HEREBY GRANTED TO USE, MODIFY, AND/OR COPY
 * THIS SOFTWARE FOR INTERNAL USE ONLY PROVIDED THAT THE ABOVE COPYRIGHT NOTICE
 * APPEARS IN ALL COPIES OF THIS SOFTWARE.
 */

#include "DummyGraphicsMacroModel_AXI_Master_Port.h"
#ifdef USE_SD_AXIv2_DummyGraphicsMacroModel
#include "SD_AXIv2_DummyGraphicsMacroModel.h"
#endif
#ifdef USE_SD_AXIv2_DummyGraphicsMacroModel2Axi
#include "SD_AXIv2_DummyGraphicsMacroModel2Axi.h"
#endif
#ifdef USE_JPEG
#include "JPEG.h"
#endif
#ifdef USE_IIP_Pseudo
#include "IIP_Pseudo.h"
#endif

template<class WrapperClass>
DummyGraphicsMacroModel_AXI_Master_Port<WrapperClass>::DummyGraphicsMacroModel_AXI_Master_Port(WrapperClass* _owner, std::string name) 
  : AXI_Master_Port(_owner, name), owner_master(_owner)
{
  // TODO: Add constructor code here.

  /* add FSL begin */
  m_aw_done_flag = 0;
  m_w_done_flag  = 0;
  m_ar_done_flag = 0;
  /* add FSL end */

}

template<class WrapperClass>
void DummyGraphicsMacroModel_AXI_Master_Port<WrapperClass>::driveTransactionCB_R()
{
  /*
  TODO: Add R combinatorial code  here
  
  //EXAMPLE:
  
  if (getSig(R_VALID))
    this->setRReady(1);
    
  */

  /* add FSL begin */
  if(m_ar_done_flag)
  {
    /* AR送信できたらRREADYを1にする */
    this->setRReady(1);
  }
  else
  {
    /* 全てのR受信終わったらRREADYを0にする */
    this->setRReady(0);
  }
  /* add FSL end */

}

template<class WrapperClass>
void DummyGraphicsMacroModel_AXI_Master_Port<WrapperClass>::driveTransactionCB_B()
{
  /*
  TODO: Add B combinatorial code  here
  
  //EXAMPLE:
  
  if (getSig(B_VALID))
    this->setBReady(1);
    
  */

  /* add FSL begin */
  if(m_aw_done_flag && m_w_done_flag)
  {
    /* AWと、全てのW送信できたらBREADYを1にする */
    this->setBReady(1);
  }
  else
  {
    /* 全てのB受信終わったらBREADYを0にする */
    this->setBReady(0);
  }
  /* add FSL end */

}

#ifdef USE_SD_AXIv2_DummyGraphicsMacroModel
template class DummyGraphicsMacroModel_AXI_Master_Port<SD_AXIv2_DummyGraphicsMacroModel>;
#endif
#ifdef USE_SD_AXIv2_DummyGraphicsMacroModel2Axi
template class DummyGraphicsMacroModel_AXI_Master_Port<SD_AXIv2_DummyGraphicsMacroModel2Axi>;
#endif
#endif
#ifdef USE_JPEG
template class DummyGraphicsMacroModel_AXI_Master_Port<JPEG>;
#endif
#ifdef USE_IIP_Pseudo
template class DummyGraphicsMacroModel_AXI_Master_Port<IIP_Pseudo>;
#endif
