/*
 *    Class definition of the SoC Designer component <BufferlessModel>
 *
 *    This code has been generated by the SoC Designer Component Wizard.
 *    Copyright (c)  2008-2010 Carbon Design Systems Inc.
 *
 * THIS SOFTWARE CONTAINS CONFIDENTIAL INFORMATION AND TRADE SECRETS OF CARBON
 * DESIGN SYSTEMS, INC.  PERMISSION IS HEREBY GRANTED TO USE, MODIFY, AND/OR COPY
 * THIS SOFTWARE FOR INTERNAL USE ONLY PROVIDED THAT THE ABOVE COPYRIGHT NOTICE
 * APPEARS IN ALL COPIES OF THIS SOFTWARE.
 */

#ifndef BufferlessModel_H
#define BufferlessModel_H

#include "maxsimCompatibility.h"

#include "eslapi/CASISaveRestore.h"

/* FSL code begin */
#include "BufferlessModel_wrapperbase.h"
#include "fj_datatype.h"

#define DATA_WIDTH_32  fj::uint32
#define DATA_WIDTH_64  fj::uint64
#define DATA_WIDTH_128 fj::uint128
#define OUTPUT_TYPE   fj::uint8
/* FSL code end */

// Place global class declarations here:

template <class WrapperClass>
class DummyGraphicsMacroModel_interrupt_SS;

template <class WrapperClass>
class DummyGraphicsMacroModel_reset_x_SS;

template <class WrapperClass>
class BufferlessModel_AXI_Master_Port;

class BufferlessModel : public CASIModule
    , public CASISaveRestore
{
  // Declare your friends here:
  friend class BufferlessModel_AXI_Master_Port<BufferlessModel>;
  friend class DummyGraphicsMacroModel_interrupt_SS<BufferlessModel>;
  friend class DummyGraphicsMacroModel_reset_x_SS<BufferlessModel>;

public:
  // Place instance declarations for the Ports here:
  BufferlessModel_AXI_Master_Port<BufferlessModel>* AXIv2_master_TMaster;
  DummyGraphicsMacroModel_interrupt_SS<BufferlessModel>* DummyGraphicsMacroModel_interrupt_SSlave[4];
  sc_port<CASISignalIF> *output_SMaster[4];
  DummyGraphicsMacroModel_reset_x_SS<BufferlessModel>* DummyGraphicsMacroModel_reset_x_SSlave;
  
  // constructor / destructor
  BufferlessModel(CASIModuleIF* c, const string &s);
  virtual ~BufferlessModel();

  // overloaded methods for clocked components
  void communicate();
  void update();

  // Implementation of CASISaveRestore interface methods
  virtual bool saveData( CASIODataStream &data );
  virtual bool restoreData( CASIIDataStream &data );

  // overloaded CASIModule methods
  string getName();
  void setParameter(const string &name, const string &value);
  string getProperty( eslapi::CASIPropertyType property );
  void init();

  void terminate();
  void reset(eslapi::CASIResetLevel level, const CASIFileMapIF *filelist);

  //Initialize the Port Properties
  void initSignalPort(CASISignalMasterIF* signalIf);
  void initAXIv2TransactionPort(CASITransactionMasterIF* transIf);

private:
  // parameters
  bool p_enableDbgMsg;
  unsigned int p_model_id;
  unsigned int p_number_of_thread;
  unsigned int p_number_of_read_outstanding;
  unsigned int p_number_of_write_outstanding;
  bool p_no_r_receive;
  bool p_no_b_receive;
  string p_time_unit;
  unsigned int p_axi_clock;
  unsigned int p_core_clock;
  string p_buffer_parameter_file_name;
  string p_fifo_parameter_file_name;
  string p_output_vcd_file_name;
  string p_output_csv_file_name;
  string p_output_summary_file_name;

  int          p_Data_Bit_Width;
  int          p_Address_Bit_Width;

  // place your private functions and data members here:
  // ...
  // This shows an example state variable for the save/restore mechanism.
  // int    exampleStateVariable;


  /* FSL code begin */
  void doneSendAW(void);
  void doneSendW(void);
  void doneSendAR(void);

  void getsendAW(void);
  void getsendW(void);
  void getsendB(void);
  void getsendAR(void);
  void getsendR(void);

  int getDataWidth(void);
  void controlInterrupt(void);
  void controlOutput(void);

  fj::uint64 m_b_count; /**< increment when AW is transfered and decrement when B is transfered */
  fj::uint64 m_r_count; /**< save ARLEN and decrement when R is transfered */

  BufferlessModel_wrapperbase *core;

  sc_signal<bool> m_signal_reset_x;
  sc_signal<bool> m_signal_interrupt[4];
  sc_signal<bool> m_signal_output[4];

  bool m_interrupt_1bit[4];
  bool m_previous_output_value[4];
  /* FSL code end */

};

#endif
